- name: play1
  hosts: all
  become:
  tasks:
   - name: Print Task1
     ansible.builtin.debug:
      msg: "Task1"

   - name: Print Task2
     ansible.builtin.debug:
       msg: "Task2"

- name: Play2
  hosts: all



