- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Restart the nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Download code and extrack
  include_role:
    name: common
    tasks_from: download

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: move the conent to dest
  ansible.builtin.copy:
            src: /srv/myfiles/foo.conf
            dest: /etc/foo.conf
