- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Restart the nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Download code and extrack
  include_role:
    name: common
    tasks_from: download
